// controllers/reportController.js
// STATUS RULES:
//   L1 = Draft       (user can set)
//   L2 = In Review   (user can set)
//   L3 = Final       (AUTO-GENERATED by backend only — hidden from UI)
//
// AUTO-L3 RULE:
//   When a vulnerability is closed (status → 'Closed') OR when a report is checked,
//   if report.status === 'L2' AND ALL vulnerabilities under it are 'Closed'
//   → automatically promote report to L3.

const Report        = require('../models/Report');
const Vulnerability = require('../models/Vulnerability');
const Organization  = require('../models/Organization');

// ── Helper: check & auto-promote to L3 ──────────────────────────────────────
// Call this after any vulnerability update/create/delete under a report
const checkAndPromoteToL3 = async (reportId, userId) => {
  const report = await Report.findOne({ _id: reportId, createdBy: userId });
  if (!report || report.status !== 'L2') return null; // only promote from L2

  const vulns = await Vulnerability.find({ reportId, createdBy: userId });
  if (vulns.length === 0) return null; // no vulnerabilities → cannot promote

  const allClosed = vulns.every(v => v.status === 'Closed');
  if (!allClosed) return null;

  // All vulns are Closed and report is L2 → promote to L3
  report.status        = 'L3';
  report.l3GeneratedAt = new Date();
  report.l3GeneratedBy = 'auto';
  await report.save();
  return report;
};

// ── Helper: strip L3 from user-submitted status (users cannot set L3) ────────
const sanitizeStatus = (s) => {
  if (s === 'L3') return 'L2'; // silently downgrade any attempt to manually set L3
  if (['L1', 'L2'].includes(s)) return s;
  return 'L1'; // default
};

// ── Helper: get org IDs owned by user ────────────────────────────────────────
const getOwnedOrgIds = (userId) =>
  Organization.find({ createdBy: userId, isActive: true }, '_id').then(orgs => orgs.map(o => o._id));

// ── EXPORTED helper so vulnerabilityController can call it ───────────────────
exports.checkAndPromoteToL3 = checkAndPromoteToL3;

// ── Create report ─────────────────────────────────────────────────────────────
// @route POST /api/reports
exports.createReport = async (req, res) => {
  try {
    const {
      organizationId, reportTitle, assessmentDate,
      reportVersion, assessorName, preparedFor, pocLink, status, tags,
    } = req.body;

    if (!organizationId) return res.status(400).json({ success: false, message: 'organizationId is required' });
    if (!reportTitle)    return res.status(400).json({ success: false, message: 'reportTitle is required' });
    if (!assessmentDate) return res.status(400).json({ success: false, message: 'assessmentDate is required' });

    const org = await Organization.findOne({ _id: organizationId, createdBy: req.user._id, isActive: true });
    if (!org) return res.status(403).json({ success: false, message: 'Organization not found or access denied' });

    const report = await Report.create({
      organizationId,
      createdBy:      req.user._id,
      reportTitle,
      assessmentDate,
      reportVersion:  reportVersion || 'v1.0',
      assessorName:   assessorName  || '',
      preparedFor:    preparedFor   || '',
      pocLink:        pocLink       || '',
      status:         sanitizeStatus(status),   // users can only set L1 or L2
      tags: Array.isArray(tags) ? tags : (tags ? tags.split(',').map(t => t.trim()).filter(Boolean) : []),
    });

    const populated = await Report.findById(report._id)
      .populate('organizationId', 'name logo')
      .populate('createdBy', 'name email');

    res.status(201).json({ success: true, data: populated });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// ── List reports ──────────────────────────────────────────────────────────────
// @route GET /api/reports
exports.getReports = async (req, res) => {
  try {
    const { orgId, status, search } = req.query;
    const userOrgIds = await getOwnedOrgIds(req.user._id);

    const query = {
      createdBy:      req.user._id,
      organizationId: { $in: userOrgIds },
    };

    if (orgId) {
      const owned = userOrgIds.map(String).includes(String(orgId));
      if (owned) query.organizationId = orgId;
      else return res.json({ success: true, count: 0, data: [] });
    }
    if (status) query.status = status;
    if (search) query.reportTitle = { $regex: search, $options: 'i' };

    const reports = await Report.find(query)
      .populate('organizationId', 'name logo')
      .populate('createdBy', 'name email')
      .sort({ createdAt: -1 });

    const withCounts = await Promise.all(reports.map(async r => {
      const counts = await Vulnerability.aggregate([
        { $match: { reportId: r._id, createdBy: req.user._id } },
        { $group: { _id: '$severity', count: { $sum: 1 } } },
      ]);
      const sev = { Critical: 0, High: 0, Medium: 0, Low: 0, Info: 0 };
      counts.forEach(c => { sev[c._id] = c.count; });
      return { ...r.toObject(), severityCounts: sev, totalVulns: counts.reduce((a, c) => a + c.count, 0) };
    }));

    res.json({ success: true, count: reports.length, data: withCounts });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// ── Get single report ─────────────────────────────────────────────────────────
// @route GET /api/reports/:id
exports.getReport = async (req, res) => {
  try {
    const userOrgIds = await getOwnedOrgIds(req.user._id);
    const report = await Report.findOne({
      _id:            req.params.id,
      createdBy:      req.user._id,
      organizationId: { $in: userOrgIds },
    })
      .populate('organizationId', 'name logo description')
      .populate('createdBy', 'name email');

    if (!report) return res.status(404).json({ success: false, message: 'Report not found' });
    res.json({ success: true, data: report });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// ── Update report ─────────────────────────────────────────────────────────────
// @route PUT /api/reports/:id
exports.updateReport = async (req, res) => {
  try {
    if (req.body.organizationId) {
      const org = await Organization.findOne({ _id: req.body.organizationId, createdBy: req.user._id });
      if (!org) return res.status(403).json({ success: false, message: 'Organization not found or access denied' });
    }

    // Prevent user from manually setting L3
    if (req.body.status) req.body.status = sanitizeStatus(req.body.status);

    const userOrgIds = await getOwnedOrgIds(req.user._id);
    const report = await Report.findOneAndUpdate(
      { _id: req.params.id, createdBy: req.user._id, organizationId: { $in: userOrgIds } },
      req.body,
      { new: true, runValidators: true }
    )
      .populate('organizationId', 'name logo')
      .populate('createdBy', 'name email');

    if (!report) return res.status(404).json({ success: false, message: 'Report not found' });

    // After update: check if it should be auto-promoted to L3
    if (report.status === 'L2') {
      const promoted = await checkAndPromoteToL3(report._id, req.user._id);
      if (promoted) {
        const refreshed = await Report.findById(report._id)
          .populate('organizationId', 'name logo')
          .populate('createdBy', 'name email');
        return res.json({ success: true, data: refreshed, autoPromoted: true, message: 'Report automatically promoted to L3 — all vulnerabilities are Closed.' });
      }
    }

    res.json({ success: true, data: report });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// ── Delete report ─────────────────────────────────────────────────────────────
// @route DELETE /api/reports/:id
exports.deleteReport = async (req, res) => {
  try {
    const userOrgIds = await getOwnedOrgIds(req.user._id);
    const report = await Report.findOneAndDelete({
      _id:            req.params.id,
      createdBy:      req.user._id,
      organizationId: { $in: userOrgIds },
    });
    if (!report) return res.status(404).json({ success: false, message: 'Report not found' });
    await Vulnerability.deleteMany({ reportId: req.params.id, createdBy: req.user._id });
    res.json({ success: true, message: 'Report and all vulnerabilities deleted' });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// ── Dashboard stats ───────────────────────────────────────────────────────────
// @route GET /api/reports/stats
exports.getDashboardStats = async (req, res) => {
  try {
    const userId     = req.user._id;
    const userOrgIds = await getOwnedOrgIds(userId);

    const [totalReports, totalOrgs, vulnStats, l3Reports] = await Promise.all([
      Report.countDocuments({ createdBy: userId, organizationId: { $in: userOrgIds } }),
      Organization.countDocuments({ createdBy: userId, isActive: true }),
      Vulnerability.aggregate([
        { $match: { createdBy: userId } },
        { $group: { _id: '$severity', count: { $sum: 1 } } },
      ]),
      Report.countDocuments({ createdBy: userId, status: 'L3' }),
    ]);

    const sev = { Critical: 0, High: 0, Medium: 0, Low: 0, Info: 0 };
    vulnStats.forEach(v => { sev[v._id] = v.count; });
    const totalVulns = Object.values(sev).reduce((a, b) => a + b, 0);

    const recentReports = await Report.find({
      createdBy:      userId,
      organizationId: { $in: userOrgIds },
    })
      .populate('organizationId', 'name logo')
      .sort({ createdAt: -1 })
      .limit(5);

    res.json({
      success: true,
      data: { totalReports, totalOrgs, totalVulns, severityBreakdown: sev, recentReports, l3Reports },
    });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};
