// models/Report.js
const mongoose = require('mongoose');

const ReportSchema = new mongoose.Schema(
  {
    organizationId: { type: mongoose.Schema.Types.ObjectId, ref: 'Organization', required: true },
    createdBy:      { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    reportTitle:    { type: String, required: [true, 'Report title is required'], trim: true },
    assessmentDate: { type: Date,   required: [true, 'Assessment date is required'] },
    reportVersion:  { type: String, default: 'v1.0' },
    assessorName:   { type: String, default: '' },
    preparedFor:    { type: String, default: '' },
    pocLink:        { type: String, default: '' },

    // ── Status levels ──────────────────────────────────────────────────────
    // L1 = Draft        → user-visible, work in progress
    // L2 = In Review    → user-visible, submitted for review
    // L3 = Final        → AUTO-GENERATED by backend only (hidden from create/edit UI)
    //                     Set automatically when report is L2 AND all vulns are Closed
    status: {
      type:    String,
      enum:    ['L1', 'L2', 'L3'],
      default: 'L1',
    },

    // L3 metadata — populated only when auto-generated
    l3GeneratedAt: { type: Date,    default: null },
    l3GeneratedBy: { type: String,  default: '' },   // 'auto' or userId

    tags: [String],
  },
  { timestamps: true }
);

ReportSchema.index({ createdBy: 1, organizationId: 1 });
ReportSchema.index({ createdBy: 1, createdAt: -1 });
ReportSchema.index({ createdBy: 1, status: 1 });

module.exports = mongoose.model('Report', ReportSchema);
